@startuml

class ToDoApp{
    main()
    start()
}

class ToDoAppController{
    importToDoList()
    exportToDoList()

    editToDoList()
    addToDoList()
    delToDoList()

    addTask()
    editTask()
    delTask()
}


class TaskTDA{
    -List<TaskTDA>

    -String taskAction
    -LocalDate date
    -boolean isComplete

    +setDate(Date date)
    +setTaskAction(String action)
    +setIsComplete()

    +getDate()
    +getTaskAction()
    +getIsComplete()
}

javafx.Application <|-- ToDoApp

ToDoApp - ToDoAppController

ToDoAppController <|-- TaskTDA


@enduml