@startuml

class ToDoApp{
    main()
    start()
}

class ToDoAppController{
    importToDoList()
    exportToDoList()

    editToDoList()
    addToDoList()
    delToDoList()

    addTask()
    editTask()
    delTask()
}

class ListTDA{
    -String listName
    -Map<String taskName, TaskTDA taskAction> tasks

    +addTask(String taskName, TaskTDA task)

    +getTask(String taskName)

    +showTasksAll()
    +showTasksInc()
    +showTasksCom()
}

class TaskTDA{
    -String taskAction
    -LocalDate date
    -boolean isComplete

    +setDate(Date date)
    +setTaskAction(String action)
    +setIsComplete()

    +getDate()
    +getTaskAction()
    +getIsComplete()
}

javafx.Application <|-- ToDoApp

ToDoApp - ToDoAppController

ToDoAppController <|-- ListTDA

ListTDA - TaskTDA

@enduml